### ISSUE TITLE
Checkboxes use a different theme, making them harder to visualize

### ISSUE THREAD

**Issue by nicoddemus** [FuturisticGoo/pyqt5-material#1]
Hi @FuturisticGoo,

I'm using the Dark Teal theme, and the checkboxes are hard to see and seem out of style related to the rest of the theme:

![image](https://user-images.githubusercontent.com/1085180/101262788-dca13b80-371f-11eb-8beb-86e450868d15.png)

Using the same script but adapted to `pyside-material`, I get a better looking checkbox:

![image](https://user-images.githubusercontent.com/1085180/101262777-d4490080-371f-11eb-8593-699a1c592500.png)

Here's the script:

```python
from PyQt5.QtWidgets import QApplication, QWidget, QHBoxLayout, QCheckBox, QPushButton
from pyqt5_material import apply_stylesheet

app = QApplication([])
apply_stylesheet(app, theme="dark_teal.xml")

widget = QWidget()

layout = QHBoxLayout(widget)
layout.addWidget(QCheckBox("Update automatically"))
layout.addWidget(QPushButton("Update"))

widget.show()
app.exec()
```

(Originally posted in https://github.com/UN-GCPDS/pyside-material/issues/7)

**Comment by FuturisticGoo** [comment]
The original fork owner has made the original fork usable for both pyqt and pyside so I am going to archive this repository. You can use `qt-material` from now on.
